server:
  port: 7003
  max-http-header-size: 102400
spring:
  application:
    name: honeycombeureka3
eureka:
  instance:
    hostname: eureka7003.com   #eureka服务器的实例名称
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}
  client:
  #是否向eureka服务注册自己
    register-with-eureka: false
    fetch-registry: false  #false表明自己是注册中心
    registry-fetch-interval-seconds: 5
    service-url: #服务监控页面
        #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  server:
    #关闭自我保护机制 防止失效的服务也被一直访问 (Spring Cloud默认该配置是 true
    enable-self-preservation: false
    #每隔30s扫描服务列表，移除失效服务
    eviction-interval-timer-in-ms: 3000
logging:
  level:
    root: info
    com.honeycom: debug
  file: logs/${spring.application.name}.log

