server:
  port: 9001
  max-http-header-size: 102400

  #Spring配置
spring:
  application:
    name: honeycomb-consumer
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    ip-address: 192.168.0.108
    instance-id: ${spring.application.name}:${server.port} #修改eureka上的默认描述信息
info:
  app_name: honeycomb-consumer
  company_name: honeycomb connection

